- name: Certificate Authority LXC
  hosts: localhost
  connection: local
  vars:
    pve_node: sol-ceres-pve
  roles:
    - role: pve_lxc
      pve_lxc_vmid: 11000
      pve_lxc_hostname: ct-ca
      pve_lxc_interfaces:
        net0: "name=eth0,bridge=virtual,firewall=1,hwaddr=BC:24:11:7D:78:FF,ip6=auto"

- name: Certificate Authority
  hosts: ca
  gather_facts: false
  pre_tasks:
    - name: Wait for LXC connection
      ansible.builtin.wait_for_connection:
  roles:
    - role: step_ca
      step_ca_user_name: "{{ ca_user_name }}"
      step_ca_user_id: "{{ ca_user_id }}"
