# TODO Add firewall rules to LXC
# TODO Add YubiKey device to LXC

- name: Certificate Authority
  hosts: ca
  gather_facts: false
  pre_tasks:
    - name: LXC "{{ pve_lxc_hostname }}"
      delegate_to: localhost
      ansible.builtin.import_role:
        name: pve_lxc
    - name: Wait for LXC connection
      ansible.builtin.wait_for_connection:
  roles:
    - step_ca
    - ca
