# TODO Add firewall rules to LXC

- name: Domain Name System
  hosts: dns
  gather_facts: false
  pre_tasks:
    - name: LXC "{{ pve_lxc_hostname }}"
      delegate_to: localhost
      ansible.builtin.import_role:
        name: pve_lxc
    - name: Wait for LXC connection
      ansible.builtin.wait_for_connection:
  roles:
    - ca
    - technitium_dns
