- name: Proxmox Backup Server
  hosts: pbs
  roles:
    - ca
  tasks:
    - name: Install sensors
      ansible.builtin.apt:
        update_cache: true
        name: lm-sensors
        state: present
