- name: Proxmox Virtual Environment
  hosts: pve
  roles:
    - ca
    - cpufreq
  tasks:
    - name: Install sensors
      ansible.builtin.apt:
        update_cache: true
        name: lm-sensors
        state: present
