collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 11.2.1
  - name: community.mysql
    version: 4.0.1
  - name: community.postgresql
    version: 4.1.0
  - name: community.proxmox
    version: 1.3.0
  - name: containers.podman
    version: 1.18.0
