- name: Certificate Authority (CA)
  ansible.builtin.import_playbook: ca.yml

- name: Domain Name System (DNS)
  ansible.builtin.import_playbook: dns.yml

- name: MariaDB
  ansible.builtin.import_playbook: mariadb.yml

- name: PostgreSQL
  ansible.builtin.import_playbook: postgresql.yml

- name: Redis
  ansible.builtin.import_playbook: redis.yml
