- name: Initialize
  ansible.builtin.import_playbook: initialize.yml

- name: Setup Network Time Protocol (NTP)
  ansible.builtin.import_playbook: ntp.yml

- name: Setup database servers
  ansible.builtin.import_playbook: database_servers.yml

- name: Setup Certificate Authority (CA)
  ansible.builtin.import_playbook: ca.yml

- name: Commit
  ansible.builtin.import_playbook: commit.yml
