# ACME
certbot_acme_domains:
  - authentik.neontech.dev
  - ldap.neontech.dev
certbot_acme_webroot: "{{ nginx_ssl_webroot }}"
certbot_acme_hooks_deploy: [nginx]
# TODO Use private CA when all OAuth applications are supported
certbot_acme_ca: null
certbot_acme_url: https://acme-v02.api.letsencrypt.org/directory
