# User
authentik_user_name: "{{ ansible_user_id }}"
authentik_user_id: "{{ ansible_user_uid }}"
authentik_group_name: "{{ authentik_user_name }}"
authentik_group_id: "{{ authentik_user_id }}"

# PostgreSQL
authentik_postgresql_host: localhost
authentik_postgresql_port: 5432
authentik_postgresql_database: authentik
authentik_postgresql_username: authentik
authentik_postgresql_password: null

# SSL
authentik_ssl_ca: "{{ mandatory(msg='default value') }}"

# Server/Worker
authentik_image: ghcr.io/goauthentik/server
authentik_image_digest: 7806ae1ae3423624fe90331e8b3dcca0afc155fac890c696dd92ddac6dc3a384 # 2026.2.3
authentik_secret_key: null

# LDAP
authentik_ldap_image: ghcr.io/goauthentik/ldap
authentik_ldap_image_digest: 91f982a01cf78291d142071e4d03fb18fcfbb47d6166c53fcf96ca17d3eb3c54 # 2026.2.3
authentik_ldap_token: null

# RADIUS
authentik_radius_image: ghcr.io/goauthentik/radius
authentik_radius_image_digest: 9c745bf3c11fc965b1a7cf6a8f2565ffafa0d25b0ffea173b9d0fae2d032fc9b # 2026.2.3
authentik_radius_token: null
