nginx_http:
  dns.neontech.dev: |
    #region DNS-over-HTTPS
    upstream dns_over_https {
      server localhost:8053;
      # Improve performance by keeping some connections alive.
      keepalive 10;
    }

    server {
      listen 80;
      listen [::]:80;
      server_name dns.neontech.dev;

      include acme_webroot;

      location / {
        return 301 https://$host$request_uri;
      }
    }

    server {
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name dns.neontech.dev;

      include ssl;
      include hsts;

      location / {
        proxy_pass http://dns_over_https;
        include proxy_params;
      }
    }
    #endregion
  technitium-dns.neontech.dev: |
    upstream technitium-dns {
      server localhost:5380;
      # Improve performance by keeping some connections alive.
      keepalive 10;
    }

    server {
      listen 80;
      listen [::]:80;
      server_name technitium-dns.neontech.dev;

      include acme_webroot;

      location / {
        return 301 https://$host$request_uri;
      }
    }

    server {
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name technitium-dns.neontech.dev;

      include ssl;
      include hsts;

      location / {
        proxy_pass http://technitium-dns;
        include proxy_params;
      }
    }

nginx_stream:
  dns.neontech.dev: |
    #region DNS-over-TCP
    upstream dns_over_tcp {
      server localhost:53800;
    }

    server {
      listen 53 proxy_protocol;
      listen [::]:53 proxy_protocol;

      proxy_pass dns_over_tcp;
    }
    #endregion
