# Version
technitium_dns_version: 15.0.1

# Download
technitium_dns_download_filename: DnsServerPortable.tar.gz
technitium_dns_download_checksum: 2eaa47654eb6e58bf08821bd170dceb59bbd035468c744bc47ba12154df28b48

# User
technitium_dns_user_name: "{{ ansible_user_id }}"
technitium_dns_user_id: "{{ ansible_user_uid }}"
technitium_dns_group_name: "{{ technitium_dns_user_name }}"
technitium_dns_group_id: "{{ technitium_dns_user_id }}"
