# Version
go_version: 1.26.6
go_os: linux
go_arch: amd64

# Download
go_download_filename: go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz
go_download_checksum: sha256:708effb774be8237570d0add163225abbdfaf4fca28b2611df167beba4feef89
